### ISSUE TITLE
bug: reports `incorrect type. Expected "object"`

### ISSUE THREAD

**Issue by BerkeleyTrue** [neoclide/coc-json#3]
A json with a top level array or string throws an error 

`[json] [W] Incorrect type. Expected "object".`

This seems to be unique to this project as opening the same file in vscode does not have this problem.

here is some examples of files that are valid json but coc-json is throwing an error: 

"foo.json"
```json
"foo"
```

"bar.json"
```json
["bar"]
```

the output of CocInfo
```
## versions

vim version: NVIM v0.3.3
node version: v8.12.0
coc.nvim version: 0.0.59
term: iTerm.app
platform: darwin

## Error messages

## Output channel: prettier

## Output channel: snippets

## Output channel: highlight
[Info  - 13:57:25] Highlight server running in node v8.12.0

```

Here is my coc extensions/package.json
```json
{
  "dependencies": {
    "coc-css": "^1.0.7",
    "coc-dictionary": "^1.2.0",
    "coc-emmet": "^1.0.9",
    "coc-emoji": "^1.2.0",
    "coc-eslint": "^1.1.0",
    "coc-highlight": "^1.0.5",
    "coc-html": "^1.0.7",
    "coc-jest": "^1.0.1",
    "coc-json": "^1.0.12",
    "coc-omni": "^1.2.0",
    "coc-prettier": "^1.1.0",
    "coc-snippets": "^2.0.2",
    "coc-stylelint": "^1.0.8",
    "coc-tag": "^1.2.0",
    "coc-tsserver": "^1.1.30",
    "coc-vetur": "^1.1.0",
    "coc-word": "^1.2.0",
    "coc-yaml": "^1.0.0",
    "coc-yank": "^1.0.2"
  }
}
```

**Comment by ckipp01** [comment]
Hey @BerkeleyTrue! I'm not sure if you're still having these issues or not, but looking into this a bit, the error message that you mentioned:
`[json] [W] Incorrect type. Expected "object".`
is actually correct if you just use `"foo"` as your json, since from my understanding, that's not valid json according to the RFC 4627 JSON standards. It must either begin with an array or an object.

I've also tried replicating your "bar.json" example, and I'm not seeing an error with associated with that when I'm trying to mimic your settings. However, I can't mimic exactly as I'm not on Mac.

Are you able to see if you can reproduce this with the latest version of coc and the plugins?
