### ISSUE TITLE
chrome extention manifest 3 not supported

### ISSUE THREAD

**Issue by redfurever** [neoclide/coc-json#58]
![image](https://user-images.githubusercontent.com/62601155/174540133-5b21462e-0bf0-4057-9ffa-4a9a37770d3a.png)
It seems to say manifest version 2 is the latest but right now it is 3.

**Comment by dougeller** [comment]
Without some explanation, I don't see this as fixed. @chemzqm closed this and marked it completed a few days ago; but the "fix" seems to have been to add a config option to enable/disable the default schemas in the catalogue. How does this fix anything? More specifically, how does it address the issue at all?

1. There is a schema that will validate both v2 and v3 of Chrome extension manifest files stored at [schemastore.org](https://json.schemastore.org/chrome-manifest.json)
2. That schema is included/referenced in the catalogue of coc-json default schemas
3. That being true, coc-json should validate and allow `manifest_version: 3` as default behaviour
4. **It does not** 

How does giving us a config option to enable/disable the default schemas solve this?

Yes, I can put the schema in the manifest file directly with `$schema`. The question is, why should I have to do that if the schema is already a default schema? Coc-json should be allowing v3 of the Chrome extension manifest as things stand right now, and it should be validating based on that version. It has the schema available to do so.

It seems this should be reopened.

**Comment by dougeller** [comment]
@chemzqm, thank you for addressing this. Unfortunately the original problem is not fixed. In fact, now we have an additional problem.

Originally, manifest.json files were not validating properly against the Chrome Extension Manifest schema included in catalog.json. Now they are not being validated against that schema at all.

For example. the schema version was recently updated from v2 to v3. In the schema the accepted values of the manifest_version property are defined by...

`    "manifest_version": {
      "type": "number",
      "description": "One integer specifying the version of the manifest file format your package requires.",
      "enum": [2, 3]
    },
`

As you can see, the schema allows for either the current version (3) or previous version (2). The original problem was that only v2 was  being accepted when coc-json validated. Since the schema is included in catalog.json, either version should be accepted **without the need to override the schema**, right?

Both attempts to fix this problem have addressed the ability to override. Why? We don't need to override anything. **We need for coc-json to validate correctly using the schema that's already in catalog.json**.

But now, since this most recent "fix", not only is the original problem not fixed, we have a new problem: Coc.json is not validating **at all** against the schema in catalog.json. 

For example: Now I can use any value at all in the `manifest_version` property and it will validate. That is now a new issue.

**Comment by chemzqm** [comment]
You need use:
```json
  "json.schemas": [
    {
      "fileMatch": ["manifest.json"],
      "url": "https://json.schemastore.org/chrome-manifest.json"
    }
  ],
```
in your coc-settings.json

**Comment by dougeller** [comment]
Since that schema is already in catalog.json, why do I need to put it in my
coc-settings.json? That seems redundant.

What is the point of it being in catalog.json if it has to be added to
coc-settings.json?

**Comment by chemzqm** [comment]
It's a fallback for json schema, you have to overwrite it when it's not work for you.
The catalog.json matches  `manifest.json` with url `https://json.schemastore.org/webextension.json`

**Comment by dougeller** [comment]
Ok. So, the reason the Chrome Extension manifest entry in catalog.json
doesn't include a match for manifest.json is because manifest.json is
already matched to another schema? So why even have the Chrome extension
schema in catalog.json at all if it has to be overridden in order to work?

Should it just be removed from catalog.json?

Thank you for helping with this! I appreciate your patience very much!

**Comment by chemzqm** [comment]
See https://github.com/neoclide/coc-json#configuration-options

**Comment by npearson72** [comment]
@chemzqm I added the field to my settings but it's still not working:

<img width="600" alt="Screen Shot 2022-09-07 at 4 08 26 PM" src="https://user-images.githubusercontent.com/1323414/188998740-bad63b19-710b-4a7a-b7e5-e1f430ea5426.png">

<img width="394" alt="Screen Shot 2022-09-07 at 4 08 40 PM" src="https://user-images.githubusercontent.com/1323414/188998750-a22d2ae4-1c41-4df8-9a47-70c8d8da4fd6.png">

Adding the schema url to the `$schema` field in the manifest works, but then is not recognized in chrome:


<img width="345" alt="Screen Shot 2022-09-07 at 4 09 31 PM" src="https://user-images.githubusercontent.com/1323414/188998824-6f8df8e7-dca1-493b-a37a-395f13f68e38.png">

Any ideas?
